# Generated by Django 5.0.3 on 2024-06-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0004_alter_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
